### ISSUE TITLE
error:  problem when running the webbot.py since 30 may 2017 (last version)

### ISSUE THREAD

**Issue by jeanbya** [picymru/webbot#2]
get an error on /dev/gpiomem --->  "You must run this on Raspberry Pi !!!"

Older version didnot have this problem  ?

try:
		with open('/dev/gpiomem') as f:
			f.read()

	except:
		exit(log.fatal('Running this application is only supported on a Raspberry Pi.'))

	# If the above test failed, they're not running on a Raspberry Pi
	robot = Robot(left=(10, 9), right=(8, 7))
	sensor = DistanceSensor(18, 17)
	robot.stop()

**Comment by matthewgall** [comment]
Apologies. Can you pull the master branch now and test it out.

**Comment by jeanbya** [comment]
Ok, shall try it out this weekend
Thanks for the quick response


Jean BYA
email: Jean.bya@outlook.be


Van: Matthew Gall <notifications@github.com>
Beantwoorden - Aan: picymru/webbot <reply@reply.github.com>
Datum: woensdag 31 mei 2017 18:23
Aan: picymru/webbot <webbot@noreply.github.com>
CC: jeanbya <jean.bya@outlook.be>, Author <author@noreply.github.com>
Onderwerp: Re: [picymru/webbot] error: problem when running the webbot.py since 30 may 2017 (last version) (#2)


Apologies. Can you pull the master branch now and test it out.
